services:
  cockroach:
    image: cockroachdb/cockroach:latest
    hostname: cockroach.devcon.io
    ports:
      - ${COCKROACH_PORT}:26257
      - ${COCKROACH_UI_PORT}:8080
    volumes:
      - ./data/cockroach:/cockroach/cockroach-data:rw
    user: "${UID}:${GID}"
    command: start-single-node --insecure

  cockroach-init:
    image: cockroachdb/cockroach:latest
    depends_on:
      - cockroach
    hostname: cockroach-init.devcon.io
    volumes:
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    entrypoint: /bin/bash
    command: /init/cockroach.sh
