services:
  cockroach1:
    image: cockroachdb/cockroach:latest
    hostname: cockroach1.devcon.io
    ports:
      - ${COCKROACH_PORT}:26257
      - ${COCKROACH_UI_PORT}:8080
    volumes:
      - ./data/cockroach1:/cockroach/cockroach-data:rw
    user: "${uid}:${gid}"
    command: start --insecure --join=cockroach1.devcon.io,cockroach2.devcon.io,cockroach3.devcon.io
  cockroach2:
    image: cockroachdb/cockroach:latest
    hostname: cockroach2.devcon.io
    volumes:
      - ./data/cockroach2:/cockroach/cockroach-data:rw
    user: "${uid}:${gid}"
    command: start --insecure --join=cockroach1.devcon.io,cockroach2.devcon.io,cockroach3.devcon.io
  cockroach3:
    image: cockroachdb/cockroach:latest
    hostname: cockroach3.devcon.io
    volumes:
      - ./data/cockroach3:/cockroach/cockroach-data:rw
    user: "${uid}:${gid}"
    command: start --insecure --join=cockroach1.devcon.io,cockroach2.devcon.io,cockroach3.devcon.io

  cockroach-init:
    image: cockroachdb/cockroach:latest
    depends_on:
      - cockroach1
      - cockroach2
      - cockroach3
    hostname: cockroach-init.devcon.io
    volumes:
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    entrypoint: /bin/bash
    command: /init/cockroach.sh
