services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    hostname: elastic.devcon.io
    ports:
      - ${ELASTIC_PORT}:9200
    environment:
      ELASTIC_PASSWORD: elasticpass
      discovery.type: single-node
      xpack.security.http.ssl.enabled: false
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data

  elastic-init:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    depends_on:
      - elastic
    hostname: elastic-init.devcon.io
    volumes:
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    command: /init/elastic.sh

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    depends_on:
      - elastic
    hostname: kibana.devcon.io
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elastic.devcon.io:9200
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: kibanapass
