services:
  cp-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: cp-zookeeper.devcon.io
    ports:
      - ${CP_ZOOKEEPER_PORT}:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  cp-broker:
    image: confluentinc/cp-server:latest
    depends_on:
      - cp-zookeeper
    hostname: cp-broker.devcon.io
    ports:
      - ${CP_KAFKA_PORT}:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: cp-zookeeper.devcon.io:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cp-broker.devcon.io:29092,PLAINTEXT_HOST://localhost:${CP_KAFKA_PORT}
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: cp-broker.devcon.io:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1

  cp-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - cp-broker
    hostname: cp-schema-registry.devcon.io
    ports:
      - ${CP_SCHEMA_REGISTRY_PORT}:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: cp-schema-registry.devcon.io
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: cp-broker.devcon.io:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  cp-control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    depends_on:
      - cp-broker
      - cp-schema-registry
    ports:
      - ${CP_CONTROL_CENTER_PORT}:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: cp-broker.devcon.io:29092
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://cp-schema-registry.devcon.io:8081
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
