services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb.devcon.io
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadbpass
    command: --bind-address=0.0.0.0

  mariadb-init:
    image: mariadb:latest
    depends_on:
      - mariadb
    hostname: mariadb-init.devcon.io
    volumes:
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    command: /init/mariadb.sh
