services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb.devcon.io
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadbpass
    command: --bind-address=0.0.0.0
