services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb.devcon.io
    ports:
      - ${MARIADB_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadbpass
    volumes:
      - ./data/mariadb:/var/lib/mysql
    user: "${UID}:${GID}"
