services:
  metastore-iceberg:
    build: metastore
    hostname: metastore-iceberg.devcon.io
    ports:
      - ${METASTORE_ICEBERG_PORT}:9083
    volumes:
      - ./data/metastore-iceberg:/home/metastore:rw
      - ./metastore/hadoop/core-site.xml:/apache/hadoop/etc/hadoop/core-site.xml:ro
      - ./metastore/hadoop/hadoop-env.sh:/apache/hadoop/etc/hadoop/hadoop-env.sh:ro
      - ./metastore/iceberg/hive-site-${METASTORE_DBTYPE}.xml:/apache/hive/conf/hive-site.xml:ro
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    command: /init/metastore.sh
