services:
  metastore-iceberg:
    build: metastore
    depends_on:
      mysql-init:
        condition: service_completed_successfully
    hostname: metastore-iceberg.devcon.io
    ports:
      - 9084:9083
    volumes:
      - ./metastore/hadoop/core-site.xml:/apache/hadoop/etc/hadoop/core-site.xml:ro
      - ./metastore/hadoop/hadoop-env.sh:/apache/hadoop/etc/hadoop/hadoop-env.sh:ro
      - ./metastore/iceberg/hive-site.xml:/apache/hive/conf/hive-site.xml:ro
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    command: /init/metastore.sh
