services:
  minio:
    image: minio/minio:latest
    hostname: minio.devcon.io
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_UI_PORT}:9001
    volumes:
      - ./data/minio:/data:rw
    user: "${UID}:${GID}"
    command: server /data --console-address ":9001"
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    hostname: minio-init.devcon.io
    volumes:
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    entrypoint: /bin/bash
    command: /init/minio.sh
