services:
  mongo:
    image: mongo:latest
    hostname: mongo.devcon.io
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongopass

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    hostname: mongo-express.devcon.io
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo.devcon.io
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
    volumes:
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    command: /init/mongo-express.sh
