services:
  mysql:
    image: mysql:latest
    hostname: mysql.devcon.io
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
    volumes:
      - ./data/mysql:/var/lib/mysql
    user: "${UID}:${GID}"

  mysql-init:
    image: mysql:latest
    depends_on:
      - mysql
    hostname: mysql-init.devcon.io
    volumes:
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    command: /init/mysql.sh
