services:
  postgres:
    image: postgres:latest
    hostname: postgres.devcon.io
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: postgrespass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    user: "${UID}:${GID}"
    command: -i

  postgres-init:
    image: postgres:latest
    depends_on:
      - postgres
    hostname: postgres-init.devcon.io
    volumes:
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    command: /init/postgres.sh
