services:
  trino:
    image: trinodb/trino:latest
    hostname: trino.devcon.io
    ports:
      - ${TRINO_PORT}:8080
    environment:
      TRINO_CATALOGS: ${TRINO_CATALOGS}
    volumes:
      - ./trino:/trino:ro
      - ./conf.sh:/conf.sh:ro
      - ./init:/init:ro
    command: /init/trino.sh
